### ISSUE TITLE
Support for nested properties

### ISSUE THREAD

**Issue by oravecz** [adaltas/node-printf#18]
While support for root property names is nice, it would really be great if nested properties could be used.

For example:

``` coffee
    printf('nested values %(nested.foo)s %(nested.bar.baz)d',
      nested:
        foo: 'work'
        bar:
          baz: 2
    ).should.eql 'nested values work 2'
```

Added support in PR #17

**Comment by wdavidw** [comment]
Closing since #17 is now merged.
