### ISSUE TITLE
variable width arguments are read in wrong order

### ISSUE THREAD

**Issue by costacosta** [adaltas/node-printf#21]
In a format like `"%*d"`, according to the POSIX spec printf expects the width to appear first.  node-printf has the arguments flipped.

The correct result according to the bash printf command:

```
$ printf "%*d" 5 4
    4
```

The equivalent C program shows the same result: http://ideone.com/pyDMkR

```C
#include <stdio.h>
 
int main(void) {
	// your code goes here
	printf("%*d", 5, 4);
	return 0;
}
```

The printj module also gives the right result: https://www.npmjs.com/package/printj

```
> require("printj").sprintf("%*d",5,4)
'    4'
```

But this module seems to flip the arguments:

```
> require("printf")("%*d",5,4)
'   5'
```

**Comment by wdavidw** [comment]
good catch

**Comment by wdavidw** [comment]
did i fixed it? i forgot

**Comment by costacosta** [comment]
No but I figured it wouldn't get fixed and it wasn't worth keeping it as an open issue.  I've since moved to a different module so even if it is fixed it wouldn't help me.
