### ISSUE TITLE
ES Modules support

### ISSUE THREAD

**Issue by 75lb** [adaltas/node-printf#27]
Any plans to release a ES Modules version we can use in modern browsers?

E.g.
```
import printj from './node_modules/printj/printj.js'
```

**Comment by 75lb** [comment]
`import printf from 'printf'` does not work natively in the browser - `'printf'` is not event a valid path.. have you tested printf in the browser using native ES6 modules?

**Comment by 75lb** [comment]
In case any one else comes across this issue, [here is a native ES6 module](https://gist.github.com/75lb/2af553f67d921aa5ce4111825007cc18) you can use until printj supports native ES6 modules.

**Comment by wdavidw** [comment]
Are you sure to be on the right page, should you be posting on this [project](https://github.com/SheetJS/printj) ?

**Comment by 75lb** [comment]
yes, you're right - this is the wrong repository.. my apologies.
